services:
  - type: web
    name: danubria-hgv-server
    env: node
    plan: free
    region: frankfurt
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: NOTIFY_EMAIL
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false

  - type: web
    name: danubria-hgv-client
    env: node
    plan: free
    region: frankfurt
    buildCommand: "cd client && npm install && npm run build"
    startCommand: "cd client && npm run preview"
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: danubria-hgv-server
          property: host
